name: Docker
on:
  workflow_dispatch:
  push:
    branches: [ main ]
env:
  ALIYUN_REGISTRY: "${{ secrets.ALIYUN_REGISTRY }}"
  ALIYUN_NAME_SPACE: "${{ secrets.ALIYUN_NAME_SPACE }}"
  ALIYUN_REGISTRY_USER: "${{ secrets.ALIYUN_REGISTRY_USER }}"
  ALIYUN_REGISTRY_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"
  MY_REGISTRY: "${{ secrets.MY_REGISTRY }}"      # 私有仓库地址（HTTP）
  MY_REGISTRY_USER: "${{ secrets.MY_REGISTRY_USER }}"
  MY_REGISTRY_PASSWORD: "${{ secrets.MY_REGISTRY_PASSWORD }}"
  MYSQL_HOST: "${{ secrets.MYSQL_HOST }}"
  MYSQL_PORT: "${{ secrets.MYSQL_PORT }}"
  MYSQL_DB: "${{ secrets.MYSQL_DB }}"
  MYSQL_USER: "${{ secrets.MYSQL_USER }}"
  MYSQL_PASSWORD: "${{ secrets.MYSQL_PASSWORD }}"

jobs:
  build:
    name: Docker Pull & Push
    runs-on: ubuntu-latest
    steps:
    # --- 安装依赖 ---
    - name: Install MySQL Client
      run: sudo apt-get update && sudo apt-get install -y mysql-client

    # --- 配置Docker ---
    - name: Fix Docker Temp Directory
      run: |
        sudo mkdir -p /var/lib/docker/tmp
        sudo chmod 777 /var/lib/docker/tmp

    - name: Configure Docker for Insecure Registry
      run: |
        echo '{"insecure-registries": ["${{ env.MY_REGISTRY }}"]}' | sudo tee /etc/docker/daemon.json
        sudo systemctl daemon-reload
        sudo systemctl restart docker

    # --- 释放磁盘空间 ---
    - name: Maximize Build Space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 2048
        swap-size-mb: 128
        remove-dotnet: 'true'
        remove-haskell: 'true'
        build-mount-path: '/var/lib/docker/buildx'  # 避免与Docker默认路径冲突

    - name: Verify Disk Space
      run: |
        echo "Before build:"
        df -hT /var/lib/docker

    # --- 初始化数据库 ---
    - name: Create MySQL Schema
      run: |
        mysql -h $MYSQL_HOST -P $MYSQL_PORT -u $MYSQL_USER -p$MYSQL_PASSWORD -e "CREATE DATABASE IF NOT EXISTS $MYSQL_DB;"
        mysql -h $MYSQL_HOST -P $MYSQL_PORT -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DB -e "
          CREATE TABLE IF NOT EXISTS push_history (
            id INT AUTO_INCREMENT PRIMARY KEY,
            registry_url VARCHAR(255) NOT NULL,
            image_name VARCHAR(255) NOT NULL,
            push_time DATETIME DEFAULT CURRENT_TIMESTAMP,
            registry_image_name VARCHAR(255) NOT NULL UNIQUE,
            push_status VARCHAR(50) NOT NULL,
            image_size BIGINT DEFAULT 0,
            digest VARCHAR(255),
            INDEX idx_registry_image (registry_image_name)
          );
        "

    # --- 准备环境 ---
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    # --- 登录仓库 ---
    - name: Login to Aliyun Registry
      run: docker login -u $ALIYUN_REGISTRY_USER -p $ALIYUN_REGISTRY_PASSWORD $ALIYUN_REGISTRY

    - name: Login to Private Registry
      run: docker login -u $MY_REGISTRY_USER -p $MY_REGISTRY_PASSWORD $MY_REGISTRY

    # --- 阿里云推送 ---
    - name: Push to Aliyun
      env:
        ALIYUN_REGISTRY: ${{ env.ALIYUN_REGISTRY }}
        ALIYUN_NAME_SPACE: ${{ env.ALIYUN_NAME_SPACE }}
      run: |
        while IFS= read -r line || [ -n "$line" ]; do
          [[ -z "$line" || "$line" =~ ^\s*# ]] && continue

          # 解析镜像信息
          image=$(echo "$line" | awk '{print $NF}' | cut -d@ -f1)
          image_name_tag=$(echo "$image" | awk -F'/' '{print $NF}')
          platform=$(echo "$line" | awk -F'--platform[ =]' '{print $2}' | awk '{print $1}')
          platform_prefix="${platform//\//_}_"
          name_space=$(echo "$image" | awk -F'/' '{if(NF==3)print $2; else if(NF==2)print $1}')
          name_space_prefix="${name_space:+${name_space}_}"

          # 生成目标镜像名
          registry_image_name="${platform_prefix}${name_space_prefix}${image_name_tag}"
          new_image="$ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/$registry_image_name"

          # 检查是否已存在
          exists=$(mysql -h $MYSQL_HOST -P $MYSQL_PORT -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DB \
            -N -e "SELECT COUNT(*) FROM push_history WHERE registry_image_name='$registry_image_name' AND registry_url='$ALIYUN_REGISTRY';")
          if [ "$exists" -eq 1 ]; then
            echo "Skipping existing: $registry_image_name (Aliyun)"
            continue
          fi

          # 处理镜像
          docker pull $line
          docker tag $image $new_image
          push_status="success"
          image_size=$(docker inspect --format='{{.Size}}' $image)
          digest=$(docker inspect --format='{{index .RepoDigests 0}}' $new_image 2>/dev/null || echo 'N/A')

          if ! docker push $new_image; then
            push_status="failed"
          fi

          # 记录到数据库
          mysql -h $MYSQL_HOST -P $MYSQL_PORT -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DB -e "
            INSERT INTO push_history (registry_url, image_name, push_status, registry_image_name, image_size, digest)
            VALUES ('$ALIYUN_REGISTRY', '$image_name_tag', '$push_status', '$registry_image_name', $image_size, '$digest');
          "

          # 清理
          docker rmi $image $new_image || true
          echo "Cleaned up $image and $new_image"
        done < images.txt

    # --- 私有仓库推送 ---
    - name: Push to Private Registry
      env:
        MY_REGISTRY: ${{ env.MY_REGISTRY }}
      run: |
        while IFS= read -r line || [ -n "$line" ]; do
          [[ -z "$line" || "$line" =~ ^\s*# ]] && continue

          # 解析镜像信息
          image=$(echo "$line" | awk '{print $NF}' | cut -d@ -f1)
          image_name_tag=$(echo "$image" | awk -F'/' '{print $NF}')
          platform=$(echo "$line" | awk -F'--platform[ =]' '{print $2}' | awk '{print $1}')
          platform_prefix="${platform//\//_}_"
          name_space=$(echo "$image" | awk -F'/' '{if(NF==3)print $2; else if(NF==2)print $1}')
          name_space_prefix="${name_space:+${name_space}_}"

          # 生成目标镜像名
          registry_image_name="${platform_prefix}${name_space_prefix}${image_name_tag}"
          new_image="$MY_REGISTRY/$registry_image_name"

          # 检查是否已存在
          exists=$(mysql -h $MYSQL_HOST -P $MYSQL_PORT -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DB \
            -N -e "SELECT COUNT(*) FROM push_history WHERE registry_image_name='$registry_image_name' AND registry_url='$MY_REGISTRY';")
          if [ "$exists" -eq 1 ]; then
            echo "Skipping existing: $registry_image_name (Private)"
            continue
          fi

          # 处理镜像
          docker pull $line
          docker tag $image $new_image
          push_status="success"
          image_size=$(docker inspect --format='{{.Size}}' $image)
          digest=$(docker inspect --format='{{index .RepoDigests 0}}' $new_image 2>/dev/null || echo 'N/A')

          if ! docker push $new_image; then
            push_status="failed"
          fi

          # 记录到数据库
          mysql -h $MYSQL_HOST -P $MYSQL_PORT -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DB -e "
            INSERT INTO push_history (registry_url, image_name, push_status, registry_image_name, image_size, digest)
            VALUES ('$MY_REGISTRY', '$image_name_tag', '$push_status', '$registry_image_name', $image_size, '$digest');
          "

          # 清理
          docker rmi $image $new_image || true
          echo "Cleaned up $image and $new_image"
        done < images.txt

    # --- 清理与验证 ---
    - name: Verify Final Disk Space
      run: |
        echo "After build:"
        df -hT /var/lib/docker
